### ISSUE TITLE
Need an access for Firserv/Reporting to one of our developers: nrupal.kallem@fiserv.com

### ISSUE THREAD

**Issue by kongaravinatha** [Fiserv/reporting#100]
Hi DevStudio team, 

Can you pls provide read and write access to one of our team mates: nrupal.kallem@fiserv.com for Fiserv/Reporting Application: 
Fead ID: f8ea42j  
First name: Nrupal
Last name: Kallem
Email: nrupal.kallem@fiserv.com

**Comment by minh-pham1** [comment]
Invitation sent, please close issue whenever they have accepted and gotten Write access to the repo.

**Comment by kongaravinatha** [comment]
thanks for helping Nrupal to login to the reporting product. hence closing the ticket.
